.\" Process this file with
.\" groff -man -T ascii foo.1
.\"
.TH GSMTPRC 1 "DECEMBER 2004" "User Manuals"
.SH NAME
gsmtprc \- SMTP Relay checker GUI Interface
.SH SYNOPSIS
.B gsmtprc
.B ...
.SH DESCRIPTION
.B gsmtprc
is a GUI interface to smtprc, see
.BR smtprc(1)  
.SH REQUIREMENTS
To run 
.BR gsmtprc
you need to have a working copy of 
.BR perl
with the 
.BR Tk
module installed.
The 
.BR "Perl Tk" 
module can be downloaded from cpan (search.cpan.org) or it can be installed 
by running 
.BR "perl -MCPAN -e 'install Tk'"
.SH BUGS
Please report all bugs to diceman@dircon.co.uk.
.SH FILES
/usr/local/bin/gsmtprc

/usr/local/bin/smtprc
.SH SEE ALSO
smtprc (1)
.SH AUTHOR
Spencer Hardy diceman@dircon.co.uk
